import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { destination, days, mood, foodPreference } = await req.json();
    const LOVABLE_API_KEY = Deno.env.get('LOVABLE_API_KEY');

    if (!LOVABLE_API_KEY) {
      throw new Error('Lovable API key not configured');
    }

    if (!destination || !days) {
      throw new Error('Destination and days are required');
    }

    console.log('Generating itinerary for:', destination, 'days:', days, 'mood:', mood, 'food:', foodPreference);

    const prompt = `Create a detailed ${days}-day travel itinerary for ${destination}.

Trip Style: ${mood || 'balanced'}
Food Preference: ${foodPreference || 'any'}

Please include:
1. Day-by-day breakdown with morning, afternoon, and evening activities
2. Specific place recommendations (restaurants, attractions, viewpoints)
3. Estimated costs in INR (₹) for each activity
4. Local tips and cultural insights
5. A summary table with total estimated budget
6. Packing essentials for this destination
7. Safety tips

Format the response in clean markdown with headers, bullet points, and tables where appropriate.
Make it practical and actionable with real place names when possible.
End with: *Generated by EnviroAI - Your Smart Travel Companion* ✨`;

    const response = await fetch('https://ai.gateway.lovable.dev/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${LOVABLE_API_KEY}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: 'google/gemini-2.5-flash',
        messages: [
          { 
            role: 'system', 
            content: 'You are an expert travel planner with deep knowledge of destinations worldwide. Create detailed, practical, and inspiring travel itineraries. Use markdown formatting for better readability.' 
          },
          { role: 'user', content: prompt }
        ],
      }),
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error('AI Gateway error:', response.status, errorText);
      
      if (response.status === 429) {
        return new Response(JSON.stringify({ error: 'Rate limit exceeded. Please try again later.' }), {
          status: 429,
          headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        });
      }
      if (response.status === 402) {
        return new Response(JSON.stringify({ error: 'AI credits exhausted. Please add credits to continue.' }), {
          status: 402,
          headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        });
      }
      
      throw new Error('Failed to generate itinerary');
    }

    const data = await response.json();
    const itinerary = data.choices[0].message.content;

    console.log('Itinerary generated successfully');

    return new Response(JSON.stringify({ itinerary }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  } catch (error) {
    console.error('Itinerary function error:', error);
    const message = error instanceof Error ? error.message : 'Unknown error';
    return new Response(JSON.stringify({ error: message }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }
});
